# Generated by Django 2.0.9 on 2020-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='_author_follow_+', to='blogArabic.author'),
        ),
    ]
