# Generated by Django 2.0.9 on 2020-05-31 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogArabic', '0004_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
