# Generated by Django 2.0.9 on 2020-06-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0005_author_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='follow',
        ),
    ]
